name: .NET Build and Deploy

on:
  push:
    branches: [ "AspNetHelloWorld", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  deploy-web-app:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/AspNetHelloWorld' || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Web App
      run: dotnet build --no-restore --configuration Release GithubActionsHelloWordWeb/GithubActionsHelloWordWeb.csproj
 
    - name: Create publish profile
      run: |
        mkdir -p GithubActionsHelloWordWeb/Properties/PublishProfiles
        echo '${{ secrets.PUBLISH_PROFILE }}' > GithubActionsHelloWordWeb/Properties/PublishProfiles/FolderProfile.pubxml
    
    - name: Publish Web App
      run: dotnet publish GithubActionsHelloWordWeb/GithubActionsHelloWordWeb.csproj --configuration Release --output ./publish --no-build --pubxml FolderProfile